---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install:
  - gem install bundler
  - rbenv rehash
script: 'bundle exec rake validate lint spec'
notifications:
  email:
    - konstantin+travisci@linuxfoundation.org
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.3
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.3
      env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
